// Real project names, delivery dates, and photos pulled from the "BROKERS - iMexico 2026"
// Google Drive folder shared for this project (organized by city > sales stage > project).
// Developer names are only filled in where a source document explicitly named them
// (DOMA, GR4, Macondo, Algi) — the rest say "Developer not confirmed" rather than guessing.
//
// IMPORTANT: unit types, bedroom/bathroom counts, prices, sizes, and amenities below are
// ILLUSTRATIVE ESTIMATES for this prototype, not the real price lists from the Drive
// (those exist as separate PDFs/spreadsheets per project that haven't been parsed yet —
// see README "Next steps"). Don't treat specific prices here as real quotes.

const DEVELOPMENTS = [
  {
    id: 1,
    project: "ALTRA",
    developer: "Developer not confirmed",
    city: "Playa del Carmen, Quintana Roo",
    lat: 20.6296, lng: -87.0739,
    deliveryDate: "Ready to move in",
    description: "Pre-sale condo development in Playa del Carmen, delivered and ready to move in.",
    amenities: ["Pool", "Gym", "Rooftop Terrace", "Coworking", "Security 24/7"],
    photos: ["1o8tIW6i7o0AoEGZrca4NwA2NHDOvw_aN", "1axpTi0rEyxMKkw4KBuQiBnRhNzuJ1qU4", "19vbXNSAbEmH0T-sPJftI_JpmN9CiGuZZ", "1MNKWbSficPTfRO3BWQLLAOJ0QdzNnzqN"],
    units: [
      { type: "Studio", bedrooms: 0, bathrooms: 1, price: 148000, size: 40, available: 5 },
      { type: "1BR", bedrooms: 1, bathrooms: 1, price: 205000, size: 58, available: 6 },
      { type: "2BR", bedrooms: 2, bathrooms: 2, price: 310000, size: 88, available: 3 },
    ],
  },
  {
    id: 2,
    project: "TIERRA MADRE",
    developer: "Developer not confirmed",
    city: "Playa del Carmen, Quintana Roo",
    lat: 20.6450, lng: -87.0850,
    deliveryDate: "Dec 2026",
    description: "Lots-and-houses development (not a condo tower) south of Playa del Carmen.",
    amenities: ["Security 24/7", "Beach Club", "BBQ Area"],
    photos: ["1zR7RP1CmSeXbHofYixYxy1lf7fikOkEa", "1hy02ChvolB7xKrYdB7fU0Z29dTXlC8t5", "1KklwjOVPzwH0Pybgup6DoIgIzf5Pho3Z", "1yR8X3JezjQEqC3X_eYgXVpn2BFMjdKBi"],
    units: [
      { type: "2BR", bedrooms: 2, bathrooms: 2, price: 285000, size: 110, available: 4 },
      { type: "3BR", bedrooms: 3, bathrooms: 2.5, price: 365000, size: 145, available: 2 },
    ],
  },
  {
    id: 3,
    project: "THE LANDMARK",
    developer: "GR4",
    city: "Playa del Carmen, Quintana Roo",
    lat: 20.6200, lng: -87.0700,
    deliveryDate: "Dec 2028",
    description: "Pre-sale condo tower in Playa del Carmen by developer GR4.",
    amenities: ["Pool", "Coworking", "Gym", "Rooftop Terrace", "Concierge"],
    photos: ["1_2fNNLqmk2uKKPJuCnLojwiQ6Xa_rCiP", "1UE1DAsynM5lpzqUYGGd-2B7BcZVDeCYz", "1Wely0d7Pv4ltOeghk9Jebk70F-n2enFb", "1e8QGEzi9v8g5h3QrJCZy6weilDcJrk-v"],
    units: [
      { type: "Studio", bedrooms: 0, bathrooms: 1, price: 165000, size: 42, available: 4 },
      { type: "1BR", bedrooms: 1, bathrooms: 1.5, price: 235000, size: 64, available: 5 },
      { type: "2BR", bedrooms: 2, bathrooms: 2, price: 355000, size: 96, available: 2 },
    ],
  },
  {
    id: 4,
    project: "MACONDO PLAYACAR",
    developer: "Macondo",
    city: "Playa del Carmen, Quintana Roo",
    lat: 20.6100, lng: -87.0650,
    deliveryDate: "Dec 2027",
    description: "Pre-sale condo development in Playacar by developer Macondo, which also has projects in Tulum and elsewhere in Playa del Carmen (Corazón, Mayakoba, PDC Fase 2/3, Punta Esmeralda).",
    amenities: ["Pool", "Gym", "Kids Club", "Security 24/7", "Parking"],
    photos: ["1mIoqOnJlowUSljcBCI0VJJ0X6oBYqL4v", "1sskaHeRAJcwadDZlzcb0Z7kx02YjClY9", "1zAXoJVdL3pIUuekPvE2PqlwLTHpfxLav", "1nkIkIWQFQ1Jd6y_LXyi7K936bN3xZA15"],
    units: [
      { type: "1BR", bedrooms: 1, bathrooms: 1, price: 195000, size: 60, available: 6 },
      { type: "2BR", bedrooms: 2, bathrooms: 2, price: 290000, size: 90, available: 4 },
    ],
  },
  {
    id: 5,
    project: "BAGÁ RIVIERA",
    developer: "DOMA",
    city: "Playa del Carmen, Quintana Roo",
    lat: 20.6350, lng: -87.0780,
    deliveryDate: "Ready to move in",
    description: "Condo development in Playa del Carmen by developer DOMA (Desarrollos Doma), delivered and ready to move in.",
    amenities: ["Pool", "Coworking", "Parking"],
    photos: ["1JsXr1C4nSn3AK-wkWMW2gU8d2mEmBP4P", "1qwVBaNpiCo25Dh6kAclnzNL0EWww7LvY", "1PB21AYrbWUodm4oN2byZE_0iarT8qEfx", "1ymHS_QUh2DPZQYnp4NasHDmhlL0FCHdp"],
    units: [
      { type: "Studio", bedrooms: 0, bathrooms: 1, price: 132000, size: 38, available: 5 },
      { type: "1BR", bedrooms: 1, bathrooms: 1, price: 178000, size: 55, available: 7 },
    ],
  },
  {
    id: 6,
    project: "SAMSARA",
    developer: "GR4",
    city: "Tulum, Quintana Roo",
    lat: 20.2114, lng: -87.4654,
    deliveryDate: "Ready to move in",
    description: "Condo development in Tulum by developer GR4 (also behind The Landmark in Playa del Carmen), delivered and ready to move in.",
    amenities: ["Pool", "Spa", "Beach Club", "Security 24/7"],
    photos: ["1G9FJiPtp_SEyByhedcM494dVHBrDrVTK", "1tfQeOV1qrfk1C6u876ArHTv_qke6USiC", "1aIzGTQV2CYbBIjq-sD_59NyQskTJRLSr", "1gfP0MvLlUhi9dASUDe79CvN4DAF6NFLe"],
    units: [
      { type: "Studio", bedrooms: 0, bathrooms: 1, price: 178000, size: 44, available: 3 },
      { type: "1BR", bedrooms: 1, bathrooms: 1.5, price: 255000, size: 66, available: 4 },
      { type: "2BR", bedrooms: 2, bathrooms: 2, price: 405000, size: 100, available: 1 },
    ],
  },
  {
    id: 7,
    project: "XUNIK",
    developer: "Algi",
    city: "Tulum, Quintana Roo",
    lat: 20.2200, lng: -87.4700,
    deliveryDate: "Ready to move in",
    description: "Condo development in Tulum by Desarrolladora Inmobiliaria Algi, built by Constructora Impala and designed by SER Arquitectura. Delivered and ready to move in.",
    amenities: ["Pool", "Gym", "Beach Club", "Concierge"],
    photos: ["1nqz5Z6tfMzqj9OWSz6IbJ7319VpPPSKV", "1rX9Z7Ef33L3a0-LTtvZLsES3L_Ld3uiJ", "1N0kMilvhh2SGQy9fpFm98hWhjfC2W-zS", "1U4GSdSGHT_G8AffxD4IhcNSngCTje1xU"],
    units: [
      { type: "1BR", bedrooms: 1, bathrooms: 1, price: 220000, size: 62, available: 3 },
      { type: "2BR", bedrooms: 2, bathrooms: 2, price: 340000, size: 94, available: 2 },
    ],
  },
  {
    id: 8,
    project: "PARAMAR BLACK",
    developer: "Developer not confirmed",
    city: "Tulum, Quintana Roo",
    lat: 20.2050, lng: -87.4600,
    deliveryDate: "Ready to move in",
    description: "Condo development in Tulum, delivered and ready to move in.",
    amenities: ["Pool", "Rooftop Terrace", "Security 24/7"],
    photos: ["1bXMBMhCgGF7yRZLzPBGl8S5JEADMU9Ok", "19ajzndKDpXzcjpS0pgJTnlL2CeS3f4pJ", "1Lq9f-3lhkGjuovR4PO4tWOiYRTbU4auO", "12d2G8XPoJvCQrZVNzSe_jPrN5m55Vrvj"],
    units: [
      { type: "Studio", bedrooms: 0, bathrooms: 1, price: 185000, size: 43, available: 4 },
      { type: "2BR", bedrooms: 2, bathrooms: 2, price: 385000, size: 95, available: 1 },
    ],
  },
  {
    id: 9,
    project: "SEREMONIA HÁBITAT",
    developer: "Developer not confirmed",
    city: "Tulum, Quintana Roo",
    lat: 20.1950, lng: -87.4550,
    deliveryDate: "Dec 2027",
    description: "Pre-sale condo development in Tulum, includes a dedicated beach club.",
    amenities: ["Pool", "Beach Club", "Gym"],
    photos: ["14b0A1yndmehJIACjPgXGpBRjqRc1AVe4", "1AMr9PZVjJIpQrJnFTuraCsZvFrwMoDVA", "14PJMgIAhBY1czY8TVUigQ_z0MibaN4pb", "1Ta4JVbX8ZzB2cZ5L2yVqHRguq6sDkNAv"],
    units: [
      { type: "1BR", bedrooms: 1, bathrooms: 1, price: 210000, size: 58, available: 5 },
      { type: "2BR", bedrooms: 2, bathrooms: 2, price: 325000, size: 89, available: 3 },
    ],
  },
  {
    id: 10,
    project: "HAMA",
    developer: "Developer not confirmed",
    city: "Mahahual, Quintana Roo",
    lat: 18.7167, lng: -87.7017,
    deliveryDate: "Ready to move in",
    description: "Condo development in Mahahual, delivered and ready to move in.",
    amenities: ["Pool", "Beach Club", "Parking"],
    photos: ["1qkiWEmUVeYHIxiFJmQrLvqqdcoZ_hLFG", "1XAevYTMt_7iNvFJpOhkx5zCDH8jJOj8x", "1ZxKa4HYRcmYdljLPTFQgBJmzAZQZrV99", "1VZTDZWHHmFTaYqga5rcS-M1g2IbPrliA"],
    units: [
      { type: "Studio", bedrooms: 0, bathrooms: 1, price: 98000, size: 38, available: 4 },
      { type: "1BR", bedrooms: 1, bathrooms: 1, price: 138000, size: 54, available: 5 },
    ],
  },
  {
    id: 11,
    project: "ALBA",
    developer: "Developer not confirmed",
    city: "Cancún, Quintana Roo",
    lat: 21.1619, lng: -86.8515,
    deliveryDate: "Ready to move in",
    description: "Condo development in Cancún, delivered and ready to move in.",
    amenities: ["Pool", "Gym", "Security 24/7", "Parking"],
    photos: ["16r44gMFYYqXayNN62tRuglk28mfPf5bN", "1tQxZ1S_-BtdtMrARdOgnWhab1U7i0bj0", "1SQ8IL-LeGvvioZAFo_wwvCDfYm1IrD7A", "1sZBLgDJweeW9WBkHbcPuLa81ZDPL2aoC"],
    units: [
      { type: "1BR", bedrooms: 1, bathrooms: 1, price: 225000, size: 63, available: 5 },
      { type: "2BR", bedrooms: 2, bathrooms: 2, price: 340000, size: 95, available: 3 },
      { type: "3BR", bedrooms: 3, bathrooms: 2.5, price: 505000, size: 142, available: 1 },
    ],
  },
  {
    id: 12,
    project: "ALUX 33",
    developer: "Developer not confirmed",
    city: "Puerto Morelos, Quintana Roo",
    lat: 20.8460, lng: -86.8756,
    deliveryDate: "Sept 2026",
    description: "Pre-sale condo tower in Puerto Morelos with a rooftop lounge.",
    amenities: ["Pool", "Rooftop Terrace", "Gym"],
    photos: ["1ZO_th26VKfiHgumLftQQCggaJuFNo2jR", "1xNmSsiaxdNVQyciNLHEEcqAgiMzB_-OX", "14u7eGnej-MGrlLAu0oFaaFgKuCLGZX1e", "1OFJAD746wd0CffO7-a91pVvvCpUfUsx1"],
    units: [
      { type: "2BR", bedrooms: 2, bathrooms: 2, price: 275000, size: 82, available: 4 },
      { type: "3BR", bedrooms: 3, bathrooms: 2, price: 360000, size: 118, available: 2 },
    ],
  },
];
